<a href="https://colab.research.google.com/github/LCaravaggio/EscueladeInnovacion/blob/main/Numpy_y_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [2]:
import numpy as np

In [22]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.full((3,3), [[0.0,0.1,0.2],[1.0,1.1,1.2],[2.0,2.1,2.3]], dtype='float16')

array([[0. , 0.1, 0.2],
       [1. , 1.1, 1.2],
       [2. , 2.1, 2.3]], dtype=float16)

In [15]:
arr=np.full((3,3), [[0.0,0.1,0.2],[1.0,1.1,1.2],[2.0,2.1,2.3]], dtype='float16')

In [16]:
arr[1,1]

1.1

In [35]:
arr.reshape(-1,1)

array([[0. ],
       [0.1],
       [0.2],
       [1. ],
       [1.1],
       [1.2],
       [2. ],
       [2.1],
       [2.3]], dtype=float16)

In [36]:
arr.reshape(1,-1)

array([[0. , 0.1, 0.2, 1. , 1.1, 1.2, 2. , 2.1, 2.3]], dtype=float16)

In [30]:
arr.T

array([[0. , 1. , 2. ],
       [0.1, 1.1, 2.1],
       [0.2, 1.2, 2.3]], dtype=float16)

In [31]:
arr.mean()

1.111

In [34]:
arr.sum(axis=0)

array([3.   , 3.299, 3.701], dtype=float16)

In [48]:
arr2=arr.reshape(1,-1)

In [49]:
arr2

array([[0. , 0.1, 0.2, 1. , 1.1, 1.2, 2. , 2.1, 2.3]], dtype=float16)

In [62]:
arr2.argsort()

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [53]:
arr2

array([[0. , 0.1, 0.2, 1. , 1.1, 1.2, 2. , 2.1, 2.3]], dtype=float16)

# Pandas