<a href="https://colab.research.google.com/github/LCaravaggio/EscueladeInnovacion/blob/main/Numpy_y_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [4]:
import numpy as np

In [ ]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full((3,3), [[0.0,0.1,0.2],[1.0,1.1,1.2],[2.0,2.1,2.3]], dtype='float16')

array([[0. , 0.1, 0.2],
       [1. , 1.1, 1.2],
       [2. , 2.1, 2.3]], dtype=float16)

In [ ]:
arr=np.full((3,3), [[0.0,0.1,0.2],[1.0,1.1,1.2],[2.0,2.1,2.3]], dtype='float16')

In [ ]:
arr[1,1]

1.1

In [ ]:
arr.reshape(-1,1)

array([[0. ],
       [0.1],
       [0.2],
       [1. ],
       [1.1],
       [1.2],
       [2. ],
       [2.1],
       [2.3]], dtype=float16)

In [ ]:
arr.reshape(1,-1)

array([[0. , 0.1, 0.2, 1. , 1.1, 1.2, 2. , 2.1, 2.3]], dtype=float16)

In [ ]:
arr.T

array([[0. , 1. , 2. ],
       [0.1, 1.1, 2.1],
       [0.2, 1.2, 2.3]], dtype=float16)

In [ ]:
arr.mean()

1.111

In [ ]:
arr.sum(axis=0)

array([3.   , 3.299, 3.701], dtype=float16)

In [ ]:
arr2=arr.reshape(1,-1)

In [ ]:
arr2

array([[0. , 0.1, 0.2, 1. , 1.1, 1.2, 2. , 2.1, 2.3]], dtype=float16)

In [ ]:
arr2.argsort()

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
arr2

array([[0. , 0.1, 0.2, 1. , 1.1, 1.2, 2. , 2.1, 2.3]], dtype=float16)

# Pandas

#### Básicas

In [2]:
import pandas as pd

In [5]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [8]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int64

In [11]:
data.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [7]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [9]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [27]:
data.iloc[:,2]

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int64

In [31]:
data.loc[::2]

one  two  three  four
Ohio    0    1      2     3
Utah    8    9     10    11

In [32]:
data[data['one']>0]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [33]:
data.loc[['Colorado', 'Utah']]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

#### Read CSV

In [34]:
!wget 'https://raw.githubusercontent.com/intro-stat-learning/ISLP_labs/stable/Auto.csv'
Auto = pd.read_csv('Auto.csv')
Auto # MPG=Miles per Galon

--2024-03-21 18:53:19--  https://raw.githubusercontent.com/intro-stat-learning/ISLP_labs/stable/Auto.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19004 (19K) [text/plain]
Saving to: ‘Auto.csv’

Auto.csv            100%[===================>]  18.56K  --.-KB/s    in 0s      

2024-03-21 18:53:19 (60.0 MB/s) - ‘Auto.csv’ saved [19004/19004]



mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0         130    3504          12.0    70   
1    15.0          8         350.0         165    3693          11.5    70   
2    18.0          8         318.0         150    3436          11.0    70   
3    16.0          8         304.0         150    3433          12.0    70   
4    17.0          8         302.0         140    3449          10.5    70   
..    ...        ...           ...         ...     ...           ...   ...   
387  27.0          4         140.0          86    2790          15.6    82   
388  44.0          4          97.0          52    2130          24.6    82   
389  32.0          4         135.0          84    2295          11.6    82   
390  28.0          4         120.0          79    2625          18.6    82   
391  31.0          4         119.0          82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
387       1            ford mustang gl  
388       2                  vw pickup  
389       1              dodge rampage  
390       1                ford ranger  
391       1                 chevy s-10  

[392 rows x 9 columns]

In [35]:
Auto.shape

(392, 9)

In [36]:
Auto.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [37]:
Auto.tail(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
390  28.0          4         120.0          79    2625          18.6    82   
391  31.0          4         119.0          82    2720          19.4    82   

     origin         name  
390       1  ford ranger  
391       1   chevy s-10